//
// Generated file, do not edit! Created by opp_msgc 3.3 from node.msg.
//

#ifndef _NODE_M_H_
#define _NODE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0303
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


/**
 * Class generated from <tt>node.msg</tt> by opp_msgc.
 * <pre>
 * message intMessage
 * {
 *   fields:
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class intMessage : public cMessage
{
  protected:
    int source_var;
    int destination_var;
    int hopCount_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const intMessage&);

  public:
    intMessage(const char *name=NULL, int kind=0);
    intMessage(const intMessage& other);
    virtual ~intMessage();
    intMessage& operator=(const intMessage& other);
    virtual cPolymorphic *dup() const {return new intMessage(*this);}
    virtual void netPack(cCommBuffer *b);
    virtual void netUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source_var);
    virtual int getDestination() const;
    virtual void setDestination(int destination_var);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount_var);
};

inline void doPacking(cCommBuffer *b, intMessage& obj) {obj.netPack(b);}
inline void doUnpacking(cCommBuffer *b, intMessage& obj) {obj.netUnpack(b);}

#endif // _NODE_M_H_
